=== AdamMil/Chrono/data/entities.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.adammil.net/Chrono/entities"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.adammil.net/Chrono/entities">

<xs:include schemaLocation="common.xsd"/>

<!-- attack -->
<xs:complexType name="attack">
  <xs:attribute name="type" type="attackType" use="required"/>
  <xs:attribute name="damage" type="damageType" default="Physical"/>
  <xs:attribute name="amount" type="intRange"/>
  <xs:attribute name="chance" type="percent"/>
</xs:complexType>

<!-- attackType -->
<xs:simpleType name="attackType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Bite"/>
    <xs:enumeration value="Breath"/>
    <xs:enumeration value="Explosion"/>
    <xs:enumeration value="Gaze"/>
    <xs:enumeration value="Kick"/>
    <xs:enumeration value="Spell"/>
    <xs:enumeration value="Spit"/>
    <xs:enumeration value="Sting"/>
    <xs:enumeration value="Touch"/>
    <xs:enumeration value="Weapon"/>
    <xs:pattern value="Spell:\w+"/>
  </xs:restriction>
</xs:simpleType>

<!-- confer -->
<xs:complexType name="confer">
  <xs:attribute name="type" type="damageType" use="required"/>
  <xs:attribute name="chance" type="percent"/>
</xs:complexType>

<!-- entity -->
<xs:complexType name="entity">
  <xs:sequence>
    <xs:element name="description" minOccurs="0" type="xs:string"/>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="attack" type="attack"/>
      <xs:element name="specialAttack" type="specialAttack"/>
      <xs:element name="resist" type="resist"/>
      <xs:element name="confer" type="confer"/>
      <xs:element name="give" type="itemDef"/>
    </xs:choice>
  </xs:sequence>

  <xs:attribute name="ai" type="xs:string"/>
  <xs:attribute name="class" type="classList"/>
  <xs:attribute name="chance" type="percent"/>
  <xs:attribute name="color" type="color"/>
  <xs:attribute name="corpseChance" type="percent"/>
  <xs:attribute name="id" type="xs:string"/>
  <xs:attribute name="inherit" type="xs:IDREF"/>
  <xs:attribute name="isBaseName" type="xs:boolean"/>
  <xs:attribute name="level" type="intRange"/>
  <xs:attribute name="flies" type="xs:boolean" default="false"/>
  <xs:attribute name="maxSpawn" type="nnint" default="120"/>
  <xs:attribute name="name" type="xs:string"/>

  <xs:attribute name="race">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Player"/>
        <xs:enumeration value="Human"/>
        <xs:enumeration value="Orc"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="size">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Tiny"/>
        <xs:enumeration value="Small"/>
        <xs:enumeration value="Medium"/>
        <xs:enumeration value="Large"/>
        <xs:enumeration value="Huge"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="socialGroup" type="xs:string"/>
  <xs:attribute name="spawnSize" type="intRange" default="1"/>
  <xs:attribute name="type" type="xs:string"/>

  <xs:attribute name="gender" default="either">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Male"/>
        <xs:enumeration value="Female"/>
        <xs:enumeration value="Neither"/>
        <xs:enumeration value="Either"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  
  <xs:attribute name="str" type="intRange"/>
  <xs:attribute name="int" type="intRange"/>
  <xs:attribute name="dex" type="intRange"/>
  <xs:attribute name="ev" type="intRange"/>
  <xs:attribute name="ac" type="intRange"/>
  <xs:attribute name="light" type="intRange"/>
  <xs:attribute name="speed" type="intRange"/>
  <xs:attribute name="maxHP" type="intRange"/>
  <xs:attribute name="maxMP" type="intRange"/>

  <xs:anyAttribute processContents="skip"/>
</xs:complexType>

<!-- entityClass -->
<xs:simpleType name="entityClass">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Melee"/>
    <xs:enumeration value="Ranged"/>
    <xs:enumeration value="Magic"/>

    <xs:enumeration value="Fighter"/>
    <xs:enumeration value="Wizard"/>
  </xs:restriction>
</xs:simpleType>

<!-- classList -->
<xs:simpleType name="classList">
  <xs:list itemType="entityClass"/>
</xs:simpleType>

<!-- entityGroup -->
<xs:complexType name="entityGroup">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element name="entity" type="entity"/>
    <xs:element name="ref">
      <xs:complexType>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="chance" type="percent"/>
      </xs:complexType>
    </xs:element>
    <xs:element name="group">
      <xs:complexType>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="chance" type="percent"/>
      </xs:complexType>
    </xs:element>
  </xs:choice>

  <xs:attribute name="name" type="xs:string"/>
</xs:complexType>

<!-- specialAttack -->
<xs:complexType name="specialAttack">
  <xs:sequence>
    <xs:element name="attack" type="attack" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>

  <xs:attribute name="name" type="xs:string" use="required"/>
  <xs:attribute name="chance" type="percent" use="required"/>
</xs:complexType>

<!-- entities -->
<xs:complexType name="entities">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element name="entityGroup" type="entityGroup"/>
    <xs:element name="entity" type="entity"/>
  </xs:choice>
</xs:complexType>

<xs:element name="entities" type="entities"/>

</xs:schema>

=== AdamMil/Chrono/data/entities.xml
<?xml version="1.0" encoding="utf-8" ?> 

<entities:entities
  xmlns:entities="http://www.adammil.net/Chrono/entities"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.adammil.net/Chrono/entities entities.xsd">

<!-- ants -->
<entityGroup name="ants">
  <entity id="_ant" type="Bug" spawnSize="1:3" ac="3" str="14:18" int="4:6" dex="8:12" gender="Neither" maxHP="8:12"/>

  <entity name="giant ant" spawnSize="2:5" inherit="_ant" chance="40" color="Brown" level="1">
    <attack amount="1d4" type="Bite"/>
  </entity>

  <entity name="soldier ant" inherit="_ant" ac="4" chance="16" level="3" color="Blue">
    <attack amount="2d4" type="Bite" chance="67"/>
    <attack amount="3:4" type="Sting" damage="DrainStr"/>
  </entity>

  <entity name="fire ant" inherit="_ant" chance="8" level="3">
    <attack amount="2d4" type="Bite" chance="50"/>
    <attack amount="2d4" type="Bite" damage="Heat"/>
    <resist type="Heat"/>
    <confer type="Heat" chance="30"/>
  </entity>
</entityGroup>

<!-- bees -->
<entityGroup name="bees">
  <entity id="_bee" type="Bug" spawnSize="3:8" ev="5" str="8:12" int="4:6" dex="10:14" flies="true" gender="Female"
          maxHP="10:14">
    <resist type="Poison"/>
    <confer type="Poison" chance="40"/>
  </entity>
  <entity name="killer bee" inherit="_bee" chance="20" level="2">
    <attack type="Sting" damage="DrainStr" amount="1:3" chance="80"/>
    <attack type="Sting" amount="1:4"/>
  </entity>
</entityGroup>

<!-- bugs -->
<entityGroup name="bugs">
  <group name="ants"/>
  <group name="bees"/>
</entityGroup>

<!-- humanoids -->
<entityGroup name="humanoids">
  <entity name="hobbit" class="Melee" type="Humanoid"
          level="1" ac="2" speed="40" chance="15" str="8:12" dex="10:14" int="7:13" ev="1" maxHP="25">
    <attack type="Weapon"/>
  </entity>

  <entity name="wizard" class="Magic" type="Humanoid"
          level="2" ac="2" speed="40" chance="10" str="8:12" dex="10:14" int="15:19" ev="1" maxHP="15" maxMP="20">
    <attack type="Spell"/>
  </entity>
</entityGroup>

<!-- quest related entities -->
<entity name="Pa" ai="fatherOfPC" type="Townsperson" race="Player" IsAdult="true" baseName="clerk" isBaseName="false">
  <give class="Gold" count="1000"/>
</entity>

<entity name="Uncle John" ai="fathersBrother" type="Townsperson" race="Player" IsAdult="true" baseName="hunter"
        isBaseName="false">
  <give class="FlamingArrow" count="40"/>
</entity>

</entities:entities>
