=== AdamMil/Chrono/trunk/data/dungeon/dungeon.xsd
<?xml version="1.0" encoding="utf-8" ?> 
<xs:schema targetNamespace="http://www.adammil.net/Chrono/dungeon"
           xmlns="http://www.adammil.net/Chrono/dungeon"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- intRange -->
<xs:simpleType name="intRange">
  <xs:restriction base="xs:string">
    <xs:pattern value="\d+(-\d+)?"/>
  </xs:restriction>
</xs:simpleType>

<!-- levels -->
<xs:complexType name="levels">
  <xs:attribute name="depth" type="intRange" use="required"/>
  <xs:attribute name="map" type="xs:string"/>
</xs:complexType>

<!-- section -->
<xs:complexType name="section">
  <xs:sequence>
    <xs:element name="levels" type="levels" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<!-- dungeon -->
<xs:complexType name="dungeon">
  <xs:sequence>
    <xs:element name="section" type="section" maxOccurs="unbounded"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:ID" use="required"/>
  <xs:attribute name="name" type="xs:string" use="required"/>
  <xs:attribute name="start" type="xs:string"/>
</xs:complexType>

<xs:element name="dungeon" type="dungeon"/>

</xs:schema>

=== AdamMil/Chrono/trunk/data/dungeon/overworld.xml
<?xml version="1.0" encoding="utf-8" ?> 

<dg:dungeon id="overworld" name="Overworld" start="gtown"
  xmlns:dg="http://www.adammil.net/Chrono/dungeon"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.adammil.net/Chrono/dungeon dungeon.xsd">

  <section name="overworld"> <!--the overworld map must be first, with a depth of 1-->
    <levels depth="1"/>
  </section>
  <section name="gtown">
    <levels depth="1"/>
  </section>
  <section name="ftown">
    <levels depth="1"/>
  </section>
  <section name="itown">
    <levels depth="1"/>
  </section>
  <section name="mtown">
    <levels depth="1"/>
  </section>
</dg:dungeon>
